
import { createClient } from '@supabase/supabase-js';

// Hardcoded fallbacks from user provision (Safe for client-side demo)
const FALLBACK_URL = "https://jgukvrgahfdtqyjckcec.supabase.co";
const FALLBACK_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndWt2cmdhaGZkdHF5amNrY2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMjM2MjIsImV4cCI6MjA4MzY5OTYyMn0.mcy4OhGR870rYFsWTfv2Az6BH7oYPyUWaoferRlFTYg";

/* 
  !!! IMPORTANT: SUPABASE DATABASE SETUP !!!
  
  If you see "relation ... does not exist" errors, you need to run this SQL in your Supabase SQL Editor:

  create table if not exists assessment_results (
    id bigint generated by default as identity primary key,
    agent_name text not null,
    score integer default 0,
    status text,
    language text,
    last_feedback text,
    updated_at timestamp with time zone default timezone('utc'::text, now()),
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  create table if not exists registrations (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    phone text,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );
  
  -- Enable Realtime for assessment_results
  alter publication supabase_realtime add table assessment_results;
*/

// Initialize Supabase Client
const getEnvVar = (key: string, fallback: string) => {
  if ((import.meta as any).env?.[key]) return (import.meta as any).env[key];
  if (typeof process !== 'undefined' && process.env?.[key]) return process.env[key];
  return fallback;
};

const supabaseUrl = getEnvVar('VITE_SUPABASE_URL', FALLBACK_URL);
const supabaseAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY', FALLBACK_ANON);

let supabase: any = null;

if (supabaseUrl && supabaseAnonKey) {
  try {
    supabase = createClient(supabaseUrl, supabaseAnonKey);
  } catch (e) {
    console.error("Failed to initialize Supabase client:", e);
  }
} else {
  console.warn("Supabase credentials missing. Database features will be disabled.");
}

export interface RegistrationData {
  name: string;
  email: string;
  phone: string;
}

export interface AssessmentResult {
  id?: number;
  agent_name: string;
  score: number;
  status: string;
  language: string;
  last_feedback?: string;
  updated_at?: string;
  created_at?: string;
}

// --- Tool for Roleplay (User registration simulation) ---
export const registerUserInDb = async (data: RegistrationData): Promise<string> => {
  if (!supabase) {
    return "Error: Database not configured.";
  }

  try {
    const { error } = await supabase
      .from('registrations')
      .insert([
        { 
          name: data.name, 
          email: data.email, 
          phone: data.phone 
        }
      ]);

    if (error) {
      // Check for missing table
      if (error.message && (error.message.includes('relation') || error.message.includes('Could not find the table'))) {
         return "System Error: The 'registrations' table does not exist in the database.";
      }
      console.error("Supabase Error (registerUser):", error.message || error);
      return `Error registering user: ${error.message}`;
    }

    return `Success! User ${data.name} (${data.email}) has been registered in the database.`;
  } catch (err: any) {
    return `System Error: ${err.message || 'Unknown error'}`;
  }
};

// --- Real Tracking (Agent Progress) ---

export const syncAssessmentProgress = async (data: AssessmentResult): Promise<number | null> => {
  if (!supabase) return null;

  try {
    // 1. If ID is provided, update specific session (prevents overwriting other agents with same name)
    if (data.id) {
      const updatePayload: any = { 
        score: data.score, 
        status: data.status, 
        language: data.language,
        updated_at: new Date().toISOString()
      };
      if (data.last_feedback) {
        updatePayload.last_feedback = data.last_feedback;
      }

      const { error } = await supabase
        .from('assessment_results')
        .update(updatePayload)
        .eq('id', data.id);

      if (error) throw error;
      return data.id;
    }

    // 2. No ID provided: Create NEW session (Start of Assessment)
    const { data: inserted, error } = await supabase
      .from('assessment_results')
      .insert([{
        agent_name: data.agent_name,
        score: data.score,
        status: data.status,
        language: data.language,
        last_feedback: data.last_feedback || ''
      }])
      .select('id')
      .single();

    if (error) {
       // Graceful fallback for duplicate name searches only if insert fails (unlikely with identity ID)
       // This part is kept minimal; we prefer creating new rows for new sessions.
       console.warn("Insert failed, trying fetch fallback", error);
    }
    
    return inserted ? inserted.id : null;

  } catch (err: any) {
    // Suppress missing table error for background sync
    const errorMsg = err.message || '';
    if (!errorMsg.includes('relation') && !errorMsg.includes('Could not find the table')) {
      console.error("Failed to sync progress:", err.message || err);
    }
    return null;
  }
};

export const deleteAssessmentResult = async (id: number): Promise<boolean> => {
  if (!supabase) return false;

  try {
    const { error } = await supabase
      .from('assessment_results')
      .delete()
      .eq('id', id);

    if (error) throw error;
    return true;
  } catch (err: any) {
    console.error("Error deleting record:", err.message || err);
    return false;
  }
};

export const fetchAdminReports = async (): Promise<AssessmentResult[]> => {
  if (!supabase) return [];

  try {
    const { data, error } = await supabase
      .from('assessment_results')
      .select('*')
      .order('updated_at', { ascending: false });

    if (error) throw error;
    return data || [];
  } catch (err: any) {
    const errorMsg = err.message || JSON.stringify(err);
    
    // Normalize missing table error
    if (errorMsg.includes('relation') || errorMsg.includes('Could not find the table')) {
      console.warn("Detected missing database tables. UI will prompt for setup.");
      throw new Error("MISSING_TABLES");
    }
    
    console.error("Error fetching reports:", errorMsg);
    throw err;
  }
};

export const subscribeToAssessmentUpdates = (callback: (payload: any) => void) => {
  if (!supabase) return { unsubscribe: () => {} };

  const channel = supabase
    .channel('realtime_assessments')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'assessment_results',
      },
      (payload: any) => {
        callback(payload);
      }
    )
    .subscribe();
    
  return channel;
};
